### PR TITLE
Fix JENKINS-45988

### PR DESCRIPTION
**Pull request by tilln**
Fixed binding mismatch between Jelly and Describable fields via tweaking JSON form data

### CODE REVIEW

**Comment by tilln** [comment]
Adding a dummy getter/setter would be less risky than messing with the ctor and Descriptor.
However, this means that the Pipeline Step would contain `previousResultsBlock: [previousResultsString: '1', value: 'true'], `
But this may not matter much since the Publisher Step DSL syntax is not actually properly defined (or rather refined) to be nicely readable.

**Comment by undera** [comment]
40508 is already fixed

**Comment by tilln** [comment]
@undera Is anyone working on a "nicer" publisher step syntax though?

**Comment by undera** [comment]
Nothing that I know of

**Pull request merged**
