### PR TITLE
Fix/support JEP-200

### PR DESCRIPTION
**Pull request by artem-fedorov**
https://issues.jenkins-ci.org/browse/JENKINS-51703

### CODE REVIEW

**Comment by artem-fedorov** [comment]
@oleg-nenashev 
Thanks for advice

**Comment by oleg-nenashev** [comment]
@artem-fedorov The fix has not been released yet from what I see. What would be the release ETA?

**Comment by artem-fedorov** [comment]
@oleg-nenashev 
Just Released

**Comment by undera** [comment]
@oleg-nenashev How can we make Artem a maintainer of this plugin? He's better than me for that :)

**Comment by artem-fedorov** [comment]
@undera 
https://wiki.jenkins.io/display/JENKINS/Hosting+Plugins#HostingPlugins-AddingMaintainerInformation
and `Request upload permissions`
https://github.com/jenkins-infra/repository-permissions-updater/blob/2b1627e571d15a4b5836236288c77f91613b47cc/permissions/plugin-performance.yml

**Comment by a-st** [comment]
@fbotner I would first need to reproduce this issue and/or provide you with a patched version so you could try if the issue is gone after reapplying the fix.

Could you maybe provide some more information abiut how you reproduced this issue? Maybe a snippet from your Jenkinsfile or a screenshot of the plugin configuration?

I'm fairly new to Jenkins plugin development but would really like to support you.

**Comment by fbotner** [comment]
Hi,

sure, we have a seed job (groovy DSL) for our jenkins jobs. This seed job create a simple `job` with the `performancePublisher` as publisher.

```
job("my job") {
    ...
    publishers {
        performancePublisher {
            sourceDataFiles("test/jmeter/*.csv")
        }
    }
    ...
}
```

The resulting config looks like

```
<hudson.plugins.performance.PerformancePublisher plugin="performance@928.vdea_0dca_55446">
<errorFailedThreshold>-1</errorFailedThreshold>
<errorUnstableThreshold>-1</errorUnstableThreshold>
<errorUnstableResponseTimeThreshold/>
<relativeFailedThresholdPositive>-1.0</relativeFailedThresholdPositive>
<relativeFailedThresholdNegative>-1.0</relativeFailedThresholdNegative>
<relativeUnstableThresholdPositive>-1.0</relativeUnstableThresholdPositive>
<relativeUnstableThresholdNegative>-1.0</relativeUnstableThresholdNegative>
<nthBuildNumber>0</nthBuildNumber>
<configType>ART</configType>
<graphType>ART</graphType>
<modeOfThreshold>false</modeOfThreshold>
<failBuildIfNoResultFile>true</failBuildIfNoResultFile>
<compareBuildPrevious>false</compareBuildPrevious>
<optionType>ART</optionType>
<modePerformancePerTestCase>false</modePerformancePerTestCase>
<excludeResponseTime>false</excludeResponseTime>
<showTrendGraphs>false</showTrendGraphs>
<modeThroughput>false</modeThroughput>
<modeEvaluation>false</modeEvaluation>
<constraints/>
<ignoreFailedBuilds>false</ignoreFailedBuilds>
<ignoreUnstableBuilds>false</ignoreUnstableBuilds>
<persistConstraintLog>false</persistConstraintLog>
<sourceDataFiles>test/jmeter/*.csv</sourceDataFiles>
<junitOutput/>
<percentiles>0,50,90,100</percentiles>
<baselineBuild>0</baselineBuild>
</hudson.plugins.performance.PerformancePublisher>
```

So no extra config, just the defaults. Everything works fine, i can start the test job and the plugin does its thing.

But after restarting the seed job (Process Job DSLs) i see this error in the jenkins logs

```
java.lang.UnsupportedOperationException: Refusing to marshal java.text.SimpleDateFormat for security reasons; see https://www.jenkins.io/redirect/class-filter/
	at hudson.util.XStream2$BlacklistedTypesConverter.marshal(XStream2.java:643)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:283)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:270)
Caused: java.lang.RuntimeException: Failed to serialize hudson.plugins.performance.parsers.AbstractParser#format for class hudson.plugins.performance.parsers.JMeterCsvParser
```

and, the now comes the ugly part, the job history of my test job is gone, all the test results and the complete jenkins job history.

I guess the is a connection between the missing job history and the error message, but i am not sure.

* Jenkins Version 2.414.1
* Performance Plugin 928.vdea_0dca_55446

**Comment by a-st** [comment]
Hi @fbotner,
I tried to reproduce this issue but I had no luck in doing so.

1. Started a fresh Jenkins container: `docker run -p 8080:8080 --name jenkins jenkins/jenkins:2.414.1-lts`
2. Installed **Job DSL** and **Performance Plugin**
3. Created a **Free Style Job** named **seed**
4. Used following snippet as **provided DSL script**:
   ```
   job("my job") {
      steps {
         shell('''cat > test.csv <<EOF
         timeStamp,elapsed,label,responseCode,responseMessage,threadName,dataType,success,bytes
         1393227741256,1300,GET /ordermgmt/login - Login Page,501,FAIL,Thread Group 1-1,text,false,3478
         1393227741257,2000,GET /ordermgmt/pre-logout,200,OK,Thread Group 1-1,text,false,19714
         1393227741258,1000,GET /ordermgmt/pre-logout,200,OK,Thread Group 1-1,text,true,19714
         EOF''')
      }
      publishers {
         performancePublisher {
             sourceDataFiles("**/*.csv")
         }
      }
   }
   ```
6. Built the **seed** job
7. Built the generated **my job** job
8. Everything worked as expected

**Comment by a-st** [comment]
@fbotner I think I managed to reproduce the issue.

In order to reproduce the issue the CSV file has to contain formatted **timeStamp** values (e.g. `2023-09-29 20:01:21.256`). Jenkins will still proceed with successfully running the job but the mentioned stacktrace is written to the log. Also after restarting Jenkins, all affected build are gone.

**Comment by a-st** [comment]
Bugfix will be provided with #240

**Comment by fbotner** [comment]
This is great, Thanks a lot

**Pull request merged**
