### PR TITLE
JENKINS-27350: Fix for uri column value not shown as link

### PR DESCRIPTION
**Pull request by hitesh22**
Re-add link to uri report, on the performance report page.
https://issues.jenkins-ci.org/browse/JENKINS-27350

### CODE REVIEW

**Comment by undera** [comment]
I tried to test this change locally, but the hyperlink leads to 404 page. Where should it point to?

**Comment by hitesh22** [comment]
URI column link from performance report page should take you to 

job/jobname/[some job number]/performance/uriReport/[reportFileName]:[URI column value].endperformanceparameter/

For example, having JMeterResults.jtl test file (from test resources) in the job workspace, gives a URI column with link text of "Home" and "Workgroup". Clicking on Workgroup will give below link.
http://localhost:8080/jenkins/job/temp/9/performance/uriReport/JMeterResults.jtl%3AWorkgroup.endperformanceparameter/

screen shot 2016-07-07 at 1 29 17 am

screen shot 2016-07-07 at 1 29 59 am

**Comment by undera** [comment]
For me, it leads to 404 page. Did you try to build the plugin with your change to make sure it helps?

**Comment by hitesh22** [comment]
Tried it again with a fresh pull from github. Works for me. These are the steps I did from a Mac. Terminal steps are copy paste if you want to try it.

In terminal:
cd /tmp
git clone https://github.com/jenkinsci/performance-plugin.git
cd performance-plugin/
mvn clean package -DskipTests
mvn hpi:run

Then In browser:
http://localhost:8080/jenkins/
Create freestyle "Temp" job. Add post-build step for Publish Performance test results report.
Add a new Jmeter report with "*.jtl"
Do one empty run.

Now In terminal:
cp /tmp/performance-plugin/src/test/resources/JMeterResults.jtl /tmp/performance-plugin/work/workspace/Temp/

Back to browser:
Run Temp job again.
Go to performance report: http://localhost:8080/jenkins/job/Temp/2/performance/
Click on Home or Workgroup link.

**Comment by undera** [comment]
Can you create new pull request? There is no option to merge this once again, GitHub gives no merge buttons

**Comment by hitesh22** [comment]
@undera Its already checked into master by you. https://github.com/jenkinsci/performance-plugin/commit/617e6b504a27fe8533a2ce4b7e46dd9f774e1729

I don't think anything else is needed. I am still new to Github's process, so maybe I missed something. Let me know and I will create a new pull request if needed.

**Comment by undera** [comment]
Then, can you install version 1.14 into your Jenkins and verify that it works well?

**Comment by hitesh22** [comment]
My changes were undone in 1.14 by someone else's fix JENKINS-28733, from commit 04537b112b440f29b0e87cccb7cf9bbb7edf7c6f.

So, basically, in 1.14, my changes were added and a later commit undid my change.

Now it is in master, but after 1.14 release.

**Comment by undera** [comment]
Sounds strange. Ok, I assume all is in the master now. Open new pull request if something else is missing.

**Pull request merged**
