### PR TITLE
[JENKINS-32650] follow up to PR #73

### PR DESCRIPTION
**Pull request by rpionke**
PR https://github.com/jenkinsci/performance-plugin/pull/73 was incomplete and was missing some getter & setters.
Its now possible to use the snippet generator without any issues.

### CODE REVIEW

**Comment by henok321** [comment]
Will there be a release containing this feature in the near future?

**Comment by undera** [comment]
I'm on a business trip now, will release it when I'm back ~2 weeks from now

**Comment by undera** [comment]
I did release 1.16

**Comment by henok321** [comment]
When will the release be available in the jenkins plugin archive. You updated the release note but the latest version is still 1.15.

https://wiki.jenkins-ci.org/display/JENKINS/Performance+Plugin

**Comment by undera** [comment]
It probably takes some time for their repos to update.

Andrey Pokhilko

**Comment by rpionke** [comment]
@henok321 the release to the update center lasts 3-4 hours. You can download the hpi file here: https://updates.jenkins-ci.org/download/plugins/performance/

**Comment by henok321** [comment]
@undera and @rpionke I updated the plugin and the following problems occured: 

* Missing PerformanceTrend in Job-View

missing_trend

* Duplicated Performance Report in Build-View

duplicated_report

* Snipped generator cannot handle relative thresholds 

`performanceReport compareBuildPrevious: false, configType: 'MRT', errorFailedThreshold: 0, errorUnstableResponseTimeThreshold: '', errorUnstableThreshold: 0, failBuildIfNoResultFile: false, modeOfThreshold: false, modePerformancePerTestCase: true, modeThroughput: false, nthBuildNumber: 0, parsers: [], relativeFailedThresholdNegative: <object of type java.lang.Double>, relativeFailedThresholdPositive: <object of type java.lang.Double>, relativeUnstableThresholdNegative: <object of type java.lang.Double>, relativeUnstableThresholdPositive: <object of type java.lang.Double>`

I had to replace <object of type java.lang.Double> manually by the correct double values.

**Pull request merged**
