### PR TITLE
Feature to enable/disable trend graphs in performance report [JENKINS-64638]

### PR DESCRIPTION
**Pull request by MalshaUdani**
This implementation is to provide user an option to enable or disable trend graphs within performance report through Performance Plugin

Ticket ID : [JENKINS-64638]

image-20201201-074421

When Enabled:

image-20201201-130237

When Disabled:

image-20201201-130408

### CODE REVIEW

**Comment by artem-fedorov** [comment]
thank you for contribution
I'll review it early the next week

Could you try help with travis ci?

**Comment by MalshaUdani** [comment]
> thank you for contribution
> I'll review it early the next week
> 
> Could you try help with travis ci?

@artem-fedorov it fails at "pip install bzt --user", seems python version should be upgraded on travis ci

**Comment by artem-fedorov** [comment]
OK. it's looks good, but i want to have trends enabled by default. I cases when you have crashes that describe in JENKINS-64638 you can disable trends. 
Could you please change default behaviour? 
@MalshaUdani

**Comment by artem-fedorov** [comment]
I fixed travis ci, please update your branch from master

**Review by artem-fedorov — COMMENTED** [review]
please, see my comments

**Comment by artem-fedorov** [comment]
Merged with changes in https://github.com/jenkinsci/performance-plugin/pull/198

**Pull request closed without merging**
