### PR TITLE
[FIXED JENKINS-26988] [FIXED JENKINS-16627][FIXED JENKINS-15736]

### PR DESCRIPTION
**Pull request by guusdk**
When (some) HttpSample are errors, graphs should not display a duration of 'zero'. More information in https://issues.jenkins-ci.org/browse/JENKINS-26988

### CODE REVIEW

**Comment by guusdk** [comment]
A basic fix for JENKINS-16627 has been added. The default JMeter parser now determines if the file is CSV or XML, and parses accordingly.

Additionally, performance is further improved by sharing the cache/serialization mechanisms with _all_ parsers (not just the JMeter one).

**Comment by guusdk** [comment]
The fix for JENKINS-15736 introduced a problem while rounding doubles to two decimals. I've committed a fix for that issue.

**Comment by guusdk** [comment]
NumberFormat instances are not thread safe. See the last comment on http://docs.oracle.com/javase/7/docs/api/java/text/NumberFormat.html

Uncontended locks in Java are pretty cheap. Better safe than sorry.

**Comment by manolo** [comment]
Thanks for contributing !

**Pull request merged**
