### PR TITLE
Show the average for the uri on the 'Performance Trend Per Test Case' view as well.

### PR DESCRIPTION
**Pull request by poolik**
See [JENKINS-40254](https://issues.jenkins-ci.org/browse/JENKINS-40254) for more info.

### CODE REVIEW

**Comment by undera** [comment]
Hi,
You'll have to cover this case with unit test. Look at codecov report above.

**Comment by undera** [comment]
it's good to have unit test for this bug

**Comment by poolik** [comment]
@undera I thought about that, but couldn't immediately come up with a easy way to test this (any suggestions?). Most likely I need to refactor the doRespondingTimeGraphPerTestCaseMode method to make the resulting dataSetBuilderAverage structure testable. I'll take a second look later today.

**Comment by undera** [comment]
I appreciate your contibution. Thanks!
Let me know when you'll find solution for unit test.

**Comment by undera** [comment]
I decided to merge this

**Pull request merged**
