### PR TITLE
Add metrics for 95th and 98th percentile for JMeter reports

### PR DESCRIPTION
**Pull request by gcaccia**
Never done a pull request before.  I made a fork and added metrics for 95th and 98th percentile for JMeter reports.  Any interest in making that part of the regular builds?

### CODE REVIEW

**Comment by SWPhantom** [comment]
I think this is a useful plugin, but I fear that populating the graphs with the higher percentiles always will have the potential for throwing everything else off. As it stands, if the 90th percentile rises too high, it occludes all of the smaller valued outputs.
I think this needs a toggle option, so that we can turn these, and the 90th percentile off from displaying if we want.

**Comment by undera** [comment]
I would accept this pull request if it would use 99% instead if 98%. 99% is more frequently used, IMO.

Also, the conflict with origin/master must be solved.

**Comment by undera** [comment]
Also, what are those "connect time" changes? They seems to be unused, thus should be removed. Or explain me how are they used?

**Comment by undera** [comment]
Okay, author has lost interest in this...

**Pull request closed without merging**
