### PR TITLE
[FIXED JENKINS-26975] Significant performance boost for Performance Plugin

### PR DESCRIPTION
**Pull request by guusdk**
This pull request introduces improvements as described in detail on https://issues.jenkins-ci.org/browse/JENKINS-26975

In short, three issues have been addressed, that each improve disc, memory and CPU utilization of the plugin. These changes turned the plugin from unworkable to lightweight in our setup.

### CODE REVIEW

**Comment by manolo** [comment]
I'll take a look to these changes, and test in my server.

**Comment by manolo** [comment]
BTW, I've merged some pending pull requests, could you rebase your patch?

**Comment by guusdk** [comment]
Try now (this is my first time merging upstream changing with a pull request - my apologies if something went wrong).

**Comment by manolo** [comment]
It works ok in my projects and it works pretty faster.
I'll release a new version soon, let's see if someone has any issue.

Thanks for contributing.

**Comment by manolo** [comment]
@guusdk Seems that this patch or #45 could have some regression problems, could you take a look to this issue ? https://issues.jenkins-ci.org/browse/JENKINS-27100

Thanks

**Comment by guusdk** [comment]
Although I'd be happy to have a look, the issue describes that the issue is
present in versions that pre-date my changes. Also, re-compilation appears
to solve the issue, according to the comments. Is my help still desired, or
has the past caught up with my late reply to your message? ;)

**Pull request merged**
